### PR TITLE
Compile updated for R, installation via install_github function

### PR DESCRIPTION
**Pull request by DannyArends**
Hey Chad et al.

Perhaps we should merge our 'master branches', this is my cleanrpack branch which can installed directly into R using the install_github() function.

I changed a couple of major things:

1) Introduced the NOMKL switch, this will disable compilation of any MKL code
2) Split the naive version into it's own file
3) Updates the package to compile and check with only 3 warnings, 3 notes
4) Added documentation for the R wrapped code versions, and made them output matrices
5) Added R functions to generate different sized matrices, with variable amount of missing data
6) Added 2 tests for R, checking back to the default cor() function

Lots of work 28 files changed, $MKL_HOME is now detected and used, so it should auto install the optimized version in R when the ENV variable exists.

Tell Mitch I'm working on a tutorial for R and a draft bioinformatics "Application Note" style article. 

Kind regards,
Danny

### CODE REVIEW

**Comment by ChadBurdyshaw** [comment]
That's great Danny. I agree we should merge this into the JICS/MPCC master
branch. I'll get that done. Thanks for your work on this.

Chad

**Comment by DannyArends** [comment]
Hey Chad,

I merged the branches together again (the vector code is now also in mine), 
Could you accept the pull request ? 
I kind of this want the merge to go forward, so that I can add the paper stuff required 
(latex templates) to the merged code. If you're OK just hit the big green button below.

If you want to check the code first on your machine. Since, I might have broken the build 
since I had to add support conditional compilation for win32/64 and nomkl.h

```
git remote add danny https://github.com/DannyArends/MPCC.git
git pull danny cleanrpack
```

run your local tests to see if it still works, after that push the branch to your master branch

**Comment by DannyArends** [comment]
Hey Chad, 

I'm getting a lot of build errors in the MKL pcc_vector code:
```
MPCC.cpp:677:63: error: invalid cast from type ‘long unsigned int’ to type ‘double’
           SB[j*n+k] += reinterpret_cast<DataType >(C_bitstring);
```

I put on line 534 an ifdef:
```C
#ifdef PCC_VECTOR
```

to exclude the non compiling g++ compiler pcc_vector code

**Comment by ChadBurdyshaw** [comment]
Thanks Danny,
Your changes are excellent. Got a little behind working on another project
so I haven't touched the MPCC stuff in a week or so. Just merged your
branch, so I think we are synced now.

Chad

**Comment by DannyArends** [comment]
Thanks for the merge, could you look into the pcc_vector errors in another branch when you have time ?
I'm starting an appnote branch off the master now for the draft of the bioinformatics application note

Tell Mitch, I'll mail him a link soon

Danny

**Comment by ChadBurdyshaw** [comment]
Danny,
The vector code is experimental and unfinished. Not surprised you are
seeing compile errors. I meant to store that version in a branch so it
wouldn't muck up the master, but your solution is fine.

Chad

**Pull request merged**
